# Generated by Django 4.0.4 on 2022-06-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0002_property_imgg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='imgg',
        ),
    ]
